load("//tools/javascript:defs.bzl", "ts_project")

package(
    default_testonly = True,
    default_visibility = ["//:__subpackages__"],
)

ts_project(
    name = "testing",
    srcs = ["fixtures.mts"],
    tsconfig = "//apps/frontend:tsconfig",
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
