load("//tools/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//:__subpackages__"])

py_library(
    name = "catalog",
    srcs = ["catalog.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//apps/backend/models:catalog",
        "//apps/backend/repositories:catalog",
    ],
)

py_library(
    name = "session",
    srcs = ["session.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//apps/backend:settings",
        "//apps/backend/domain/session:exceptions",
        "//apps/backend/domain/session:run_plan_builder",
        "//apps/backend/domain/session:scoring",
        "//apps/backend/models:plan",
        "//apps/backend/models:scoring",
        "//apps/backend/models:session",
        "//apps/backend/repositories:catalog",
        "//apps/backend/repositories/session",
        "//apps/backend/repositories/session:plan",
        "//apps/backend/repositories/session:scoring",
    ],
)

py_test(
    name = "catalog_test",
    srcs = ["catalog_test.py"],
    deps = [
        ":catalog",
        "//apps/backend:conftest",
        "//apps/backend:settings",
        "//apps/backend/repositories:catalog",
        "//libs/testing:io",
    ],
)

py_test(
    name = "session_test",
    srcs = ["session_test.py"],
    deps = [
        ":session",
        "//apps/backend:conftest",
        "//apps/backend:settings",
        "//apps/backend/domain/session:exceptions",
        "//apps/backend/models:catalog",
        "//apps/backend/models:plan",
        "//apps/backend/models:scoring",
        "//apps/backend/models:session",
        "//apps/backend/repositories:catalog",
        "//apps/backend/repositories/session",
        "//apps/backend/repositories/session:plan",
        "//apps/backend/repositories/session:scoring",
        "@pip//pytest",
    ],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
