load("//tools/javascript:defs.bzl", "ts_project")

package(default_visibility = ["//:__subpackages__"])

ts_project(
    name = "pages",
    srcs = [
        "block_intro.mts",
        "catalog.mts",
        "result.mts",
        "review.mts",
        "trial.mts",
    ],
    declaration = True,
    tsconfig = "//apps/frontend:tsconfig",
    visibility = ["//:__subpackages__"],
    deps = [
        "//apps/frontend/core",
        "//apps/frontend/state",
        "//apps/frontend/ui",
    ],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
