package(default_visibility = ["//:__subpackages__"])

filegroup(
    name = "american",
    srcs = ["american.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "base",
    srcs = ["base.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "foreign",
    srcs = ["foreign.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
