load("//tools/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//:__subpackages__"])

py_library(
    name = "catalog",
    srcs = ["catalog.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//apps/backend:settings",
        "//apps/backend/domain/iat:spec_models",
        "//apps/backend/models:catalog",
    ],
)

py_test(
    name = "catalog_test",
    srcs = ["catalog_test.py"],
    deps = [
        ":catalog",
        "//apps/backend:conftest",
        "//apps/backend:settings",
        "//libs/testing:io",
        "@pip//pytest",
    ],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
