load("//tools/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//:__subpackages__"])

py_library(
    name = "iat",
    srcs = ["iat.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//apps/backend:settings",
        "//apps/backend/domain/iat:models",
        "//apps/backend/domain/iat:spec_models",
    ],
)

py_test(
    name = "iat_test",
    srcs = ["iat_test.py"],
    deps = [
        ":iat",
        "//apps/backend:conftest",
        "//apps/backend:settings",
        "//libs/testing:io",
        "@pip//pytest",
    ],
)

py_test(
    name = "session_test",
    srcs = ["session_test.py"],
    deps = [
        "//apps/backend:conftest",
        "//apps/backend:database",
        "//apps/backend/domain/session:exceptions",
        "//apps/backend/domain/session:models",
        "//apps/backend/repositories/session:repository",
        "//apps/backend/repositories/session:schema",
        "@pip//pytest",
        "@pip//sqlalchemy",
    ],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
