[project]
name = "iat"
version = "0"
dependencies = [
    "accelerate>=1.1.0",
    "bazel-runfiles>=2.0.1",
    "diffusers>=0.38.0",
    "fastapi>=0.115.12",
    "gdown>=5.2.0",
    "huggingface-hub>=0.27.0",
    "httpx>=0.28.1",
    "ipython>=9.11.0",
    "loguru>=0.7.3",
    "pillow>=11.0.0",
    "protobuf>=5.29.0",
    "pydoclint>=0.8.3",
    "pytest>=8.3.5",
    "pyyaml>=6.0.2",
    "safetensors>=0.8.0rc0",
    "sentencepiece>=0.2.0",
    "python-multipart>=0.0.20",
    "ruff>=0.11.4",
    "sqlalchemy>=2.0.40",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "tomli-w>=1.2.0",
    "transformers>=4.46.0",
    "ty>=0.0.1a16",
    "uvicorn>=0.34.0",
    "typer>=0.24.1",
    "yamllint>=1.38.0",
]
