load("@aspect_rules_esbuild//esbuild:defs.bzl", "esbuild")
load("@aspect_rules_ts//ts:defs.bzl", "ts_config")
load("@bazel_lib//lib:copy_to_directory.bzl", "copy_to_directory")
load("//tools/javascript:defs.bzl", "ts_project")

package(default_visibility = ["//:__subpackages__"])

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = [":__subpackages__"],
    deps = [
        "//:node_modules/@types/node",
        "//:tsconfig",
    ],
)

esbuild(
    name = "bundle",
    srcs = [
        "controller.mts",
        "main.mts",
        ":frontend",
    ],
    entry_point = "main.mts",
    format = "esm",
    output = "main.js",
    platform = "browser",
    target = ["es2022"],
    tsconfig = ":tsconfig",
    deps = [":frontend"],
)

copy_to_directory(
    name = "dist",
    srcs = [
        "app.css",
        "index.html",
        ":bundle",
        "//:node_modules/normalize.css",
    ],
    out = "dist",
    replace_prefixes = {
        "app.css": "assets/app.css",
        "main.js": "assets/main.js",
        "normalize.css": "assets/normalize.css",
    },
)

ts_project(
    name = "frontend",
    srcs = [
        "controller.mts",
        "main.mts",
        "render.mts",
    ],
    declaration = True,
    tsconfig = ":tsconfig",
    visibility = ["//:__subpackages__"],
    deps = [
        "//apps/frontend/core",
        "//apps/frontend/session",
        "//apps/frontend/state",
        "//apps/frontend/ui",
        "//apps/frontend/ui/pages",
    ],
)
