jobs:
  - spec: ./baseline-text-text.yaml
    output_dir: ../evaluation-results/baseline-text-text
  - spec: ./baseline-image-text.yaml
    output_dir: ../evaluation-results/baseline-image-text
  - spec: ./baseline-image-image.yaml
    output_dir: ../evaluation-results/baseline-image-image
  - spec: ./delay-700.yaml
    output_dir: ../evaluation-results/delay-700
  - spec: ./cpu-throttling.yaml
    output_dir: ../evaluation-results/cpu-throttling
  - spec: ./network-degradation.yaml
    output_dir: ../evaluation-results/network-degradation
