jobs:
  - spec: ./baseline-text-text.yaml
    output_dir: ../../apps/evaluation/results/baseline-text-text
  - spec: ./baseline-image-text.yaml
    output_dir: ../../apps/evaluation/results/baseline-image-text
  - spec: ./baseline-image-image.yaml
    output_dir: ../../apps/evaluation/results/baseline-image-image
  - spec: ./cpu-throttling-light.yaml
    output_dir: ../../apps/evaluation/results/cpu-throttling-light
  - spec: ./cpu-throttling-moderate.yaml
    output_dir: ../../apps/evaluation/results/cpu-throttling-moderate
  - spec: ./cpu-throttling-heavy.yaml
    output_dir: ../../apps/evaluation/results/cpu-throttling-heavy
  - spec: ./network-degradation-wifi-constrained.yaml
    output_dir: ../../apps/evaluation/results/network-degradation-wifi-constrained
  - spec: ./network-degradation-fast-3g.yaml
    output_dir: ../../apps/evaluation/results/network-degradation-fast-3g
  - spec: ./network-degradation-slow-3g.yaml
    output_dir: ../../apps/evaluation/results/network-degradation-slow-3g
