package(default_visibility = ["//:__subpackages__"])

filegroup(
    name = "all",
    srcs = ["all.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "base",
    srcs = ["base.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "readme",
    srcs = ["README.md"],
    tags = ["markdown"],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

filegroup(
    name = "baseline-image-image",
    srcs = ["baseline-image-image.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "baseline-image-text",
    srcs = ["baseline-image-text.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "baseline-text-text",
    srcs = ["baseline-text-text.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "cpu-throttling",
    srcs = ["cpu-throttling.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "network-degradation",
    srcs = ["network-degradation.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "delay-1000",
    srcs = ["delay-1000.yaml"],
    tags = ["yaml"],
)
