load("//tools/python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//:__subpackages__"])

py_library(
    name = "database_base",
    srcs = ["database_base.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//sqlalchemy"],
)

py_library(
    name = "database_schema",
    srcs = ["database_schema.py"],
    visibility = ["//:__subpackages__"],
    deps = ["//apps/backend/repositories/session:schema"],
)

py_library(
    name = "database",
    srcs = ["database.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":database_base",
        ":database_schema",
        "@pip//sqlalchemy",
    ],
)

py_library(
    name = "dependencies",
    srcs = ["dependencies.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":settings",
        "//apps/backend/repositories:iat",
        "//apps/backend/repositories/session:repository",
        "//apps/backend/services:iat",
        "//apps/backend/services:session",
        "@pip//fastapi",
        "@pip//sqlalchemy",
    ],
)

py_library(
    name = "app",
    srcs = ["app.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":database",
        ":dependencies",
        ":settings",
        "//apps/backend/repositories:iat",
        "//apps/backend/routers:iats",
        "//apps/backend/routers:sessions",
        "//apps/backend/routers:stimuli",
        "//apps/backend/services:iat",
        "@pip//fastapi",
    ],
)

py_binary(
    name = "main",
    srcs = ["main.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":app",
        ":settings",
        "@pip//uvicorn",
    ],
)

py_library(
    name = "settings",
    srcs = ["settings.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//libs/bazel:workspace",
        "//libs/config",
        "//libs/path",
        "//libs/pydantic:types",
        "@pip//pydantic",
    ],
)

py_test(
    name = "settings_test",
    srcs = ["settings_test.py"],
    deps = [
        ":conftest",
        ":settings",
        "//libs/testing:io",
        "@pip//pydantic",
        "@pip//pytest",
    ],
)

py_test(
    name = "dependencies_test",
    srcs = ["dependencies_test.py"],
    deps = [
        ":conftest",
        ":dependencies",
        "//apps/backend/domain/session:models",
        "//third_party/python/fastapi:testclient",
        "@pip//fastapi",
        "@pip//sqlalchemy",
    ],
)

py_test(
    name = "app_test",
    srcs = ["app_test.py"],
    deps = [
        ":app",
        ":conftest",
        ":settings",
        "//apps/backend/models:iat",
        "//libs/testing:io",
        "//third_party/python/fastapi:testclient",
        "@pip//pydantic",
        "@pip//pytest",
    ],
)

py_test(
    name = "database_test",
    srcs = ["database_test.py"],
    deps = [
        ":conftest",
        ":database",
        "@pip//sqlalchemy",
    ],
)

filegroup(
    name = "readme",
    srcs = ["README.md"],
    tags = ["markdown"],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":database",
        ":dependencies",
        ":settings",
        "//apps/backend/repositories:iat",
        "//apps/backend/services:iat",
        "//libs/testing:io",
        "@pip//pytest",
    ],
)
