package(default_visibility = ["//:__subpackages__"])

filegroup(
    name = "android-chrome",
    srcs = ["android-chrome.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "linux-chrome",
    srcs = ["linux-chrome.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "manifest",
    srcs = ["manifest.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "win-chrome",
    srcs = ["win-chrome.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
