load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_test")
load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//:__subpackages__"])

js_binary(
    name = "lock",
    args = [
        "generate",
        "$(rootpath @pnpm//:pnpm)",
        "$(rootpath //:package.json)",
        "$(rootpath //:pnpm-lock.yaml)",
    ],
    copy_data_to_bin = False,
    data = [
        "//:package.json",
        "//:pnpm-lock.yaml",
        "@pnpm",
    ],
    entry_point = "lock_lib.mjs",
    tags = ["manual"],
    visibility = ["//:__subpackages__"],
)

js_test(
    name = "lock_test",
    size = "small",
    args = [
        "verify",
        "$(rootpath @pnpm//:pnpm)",
        "$(rootpath //:package.json)",
        "$(rootpath //:pnpm-lock.yaml)",
    ],
    copy_data_to_bin = False,
    data = [
        "//:package.json",
        "//:pnpm-lock.yaml",
        "@pnpm",
    ],
    entry_point = "lock_lib.mjs",
    tags = ["manual"],
)

js_binary(
    name = "node_modules",
    data = ["node_modules.mjs"],
    entry_point = "node_modules.mjs",
    tags = ["manual"],
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
    deps = [
        "@aspect_rules_swc//swc:defs",
        "@aspect_rules_ts//ts:defs",
        "@bazel_skylib//lib:partial",
    ],
)
