load("//tools/python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//:__subpackages__"])

py_library(
    name = "stable_diffusion_3_5",
    srcs = ["stable_diffusion_3_5.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":specs",
        "@pip//accelerate",
        "@pip//diffusers",
        "@pip//pillow",
        "@pip//torch",
        "@pip//torchvision",
        "@pip//transformers",
    ],
)

py_binary(
    name = "main",
    srcs = ["main.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":specs",
        ":stable_diffusion_3_5",
        "//libs/bazel:workspace",
        "@pip//diffusers",
        "@pip//huggingface_hub",
        "@pip//transformers",
        "@pip//typer",
    ],
)

py_library(
    name = "specs",
    srcs = ["specs.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//libs/config",
        "//libs/config:extending_config",
        "//libs/pydantic:types",
        "@pip//pydantic",
    ],
)

py_test(
    name = "specs_test",
    srcs = ["specs_test.py"],
    deps = [
        ":specs",
        "@pip//pydantic",
        "@pip//pytest",
        "@pip//pyyaml",
    ],
)

filegroup(
    name = "readme",
    srcs = ["README.md"],
    tags = ["markdown"],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
