jobs:
  - spec: ./face/female-asian.yaml
    output_dir: ../stimuli/face/female-asian
  - spec: ./face/female-black.yaml
    output_dir: ../stimuli/face/female-black
  - spec: ./face/female-white-caucasian.yaml
    output_dir: ../stimuli/face/female-white-caucasian
  - spec: ./face/female-white-caucasian-fat.yaml
    output_dir: ../stimuli/face/female-white-caucasian-fat
  - spec: ./face/female-white-caucasian-old.yaml
    output_dir: ../stimuli/face/female-white-caucasian-old
  - spec: ./face/female-white-caucasian-thin.yaml
    output_dir: ../stimuli/face/female-white-caucasian-thin
  - spec: ./face/female-white-caucasian-young.yaml
    output_dir: ../stimuli/face/female-white-caucasian-young
  - spec: ./face/male-asian.yaml
    output_dir: ../stimuli/face/male-asian
  - spec: ./face/male-black.yaml
    output_dir: ../stimuli/face/male-black
  - spec: ./face/male-white-caucasian.yaml
    output_dir: ../stimuli/face/male-white-caucasian
  - spec: ./face/male-white-caucasian-fat.yaml
    output_dir: ../stimuli/face/male-white-caucasian-fat
  - spec: ./face/male-white-caucasian-old.yaml
    output_dir: ../stimuli/face/male-white-caucasian-old
  - spec: ./face/male-white-caucasian-thin.yaml
    output_dir: ../stimuli/face/male-white-caucasian-thin
  - spec: ./face/male-white-caucasian-young.yaml
    output_dir: ../stimuli/face/male-white-caucasian-young
