load("//tools/javascript:defs.bzl", "ts_project")

package(default_visibility = ["//:__subpackages__"])

ts_project(
    name = "core",
    srcs = [
        "api.mts",
        "api_adapter.mts",
        "config.mts",
        "errors.mts",
        "http.mts",
        "startup.mts",
        "utils.mts",
    ],
    declaration = True,
    tsconfig = "//apps/frontend:tsconfig",
    visibility = ["//:__subpackages__"],
    deps = [
        "//:node_modules/openapi-fetch",
        "//apps/api:backend",
        "//apps/frontend/state",
    ],
)

ts_project(
    name = "core_tests",
    testonly = True,
    srcs = [
        "api_adapter_test.mts",
        "api_test.mts",
        "http_test.mts",
        "startup_test.mts",
    ],
    declaration = True,
    tsconfig = "//apps/frontend:tsconfig",
    deps = [
        ":core",
        "//:node_modules/@types/node",
        "//apps/api:backend",
        "//apps/frontend/core/testing",
        "//apps/frontend/state",
    ],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
