load("//tools/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//:__subpackages__"])

py_library(
    name = "catalog",
    srcs = ["catalog.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":stimuli",
        "//apps/backend:dependencies",
        "//apps/backend/schemas:catalog",
        "//apps/backend/services:catalog",
        "@pip//fastapi",
    ],
)

py_library(
    name = "stimuli",
    srcs = ["stimuli.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//apps/backend:dependencies",
        "//apps/backend/services:catalog",
        "@pip//fastapi",
    ],
)

py_library(
    name = "sessions",
    srcs = ["sessions.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":stimuli",
        "//apps/backend:dependencies",
        "//apps/backend/domain/session:exceptions",
        "//apps/backend/schemas:session",
        "//apps/backend/services:session",
        "@pip//fastapi",
    ],
)

py_test(
    name = "catalog_test",
    srcs = ["catalog_test.py"],
    deps = [
        ":conftest",
        "//apps/backend:conftest",
        "//third_party/python/fastapi:testclient",
    ],
)

py_test(
    name = "stimuli_test",
    srcs = ["stimuli_test.py"],
    deps = [
        ":conftest",
        "//apps/backend:conftest",
        "//libs/testing:io",
        "//third_party/python/fastapi:testclient",
        "@pip//httpx",
    ],
)

py_test(
    name = "sessions_test",
    srcs = ["sessions_test.py"],
    deps = [
        ":conftest",
        "//apps/backend:conftest",
        "//apps/backend/schemas:session",
        "//third_party/python/fastapi:testclient",
        "@pip//pytest",
    ],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":catalog",
        ":stimuli",
        "//apps/backend:app",
        "//apps/backend:database",
        "//apps/backend:dependencies",
        "//apps/backend:settings",
        "//apps/backend/repositories:catalog",
        "//apps/backend/services:catalog",
        "//libs/testing:io",
        "//third_party/python/fastapi:testclient",
        "@pip//fastapi",
        "@pip//pytest",
        "@pip//sqlalchemy",
    ],
)
