extends: ../base.yaml
stimuli_generation:
  prompts:
    negative_prompt: >-
      text, watermark, logo,
      multiple people, extra face, extra limbs,
      cropped head, profile view, head turned away,
      dramatic lighting, open mouth, smiling,
      accessories, busy background, blur, low quality,
      deformed face, full body, visible hands, visible arms,
      distant shot
