"""Download Project Implicit study materials into the local assets tree."""

from __future__ import annotations

from typing import TYPE_CHECKING

import gdown
from gdown.exceptions import FileURLRetrievalError, FolderContentsMaximumLimitError

from backend.app.config import DownloadSourceConfig, load_download_source_configs

if TYPE_CHECKING:
    from pathlib import Path

    from backend.app.config import Settings


class UnknownAssetSourcesError(Exception):
    """The download request referenced source slugs not in the manifest."""

    def __init__(self, source_slugs: list[str]) -> None:
        """Store the unknown source slugs for CLI reporting."""
        self.source_slugs = source_slugs
        message = f"Unknown source slugs: {', '.join(source_slugs)}"
        super().__init__(message)


class AssetDownloadError(Exception):
    """A Project Implicit source download failed."""

    def __init__(self, source_slug: str, cause: Exception) -> None:
        """Store source context for CLI reporting."""
        self.source_slug = source_slug
        self.cause = cause
        super().__init__(f"{source_slug}: {cause}")


def _download_source(source: DownloadSourceConfig, base_dir: Path) -> None:
    target_dir = base_dir / source.slug
    target_dir.mkdir(parents=True, exist_ok=True)

    if "/folders/" in source.link:
        downloaded = gdown.download_folder(
            url=source.link,
            output=str(target_dir),
            quiet=False,
            remaining_ok=True,
            use_cookies=False,
            resume=True,
        )
    else:
        downloaded = gdown.download(
            url=source.link,
            output=str(target_dir / source.slug),
            quiet=False,
            fuzzy=True,
            resume=True,
            use_cookies=False,
        )

    if downloaded is None:
        kind = "folder" if "/folders/" in source.link else "file"
        msg = f"Could not download {kind} contents for {source.slug}."
        raise ValueError(msg)


def _write_manifest(base_dir: Path, sources: list[DownloadSourceConfig]) -> None:
    lines = [
        "# Project Implicit Sources",
        "",
        "Generated by `python -m backend.app.cli download-assets`.",
        "Do not commit downloaded files.",
        "",
        "## Sources",
        "",
    ]
    for source in sources:
        lines.append(f"- `{source.slug}`")
        lines.append(f"  Link: `{source.link}`")
    (base_dir / "README.local.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _select_sources(
    available_sources: list[DownloadSourceConfig],
    requested_source_slugs: set[str],
) -> list[DownloadSourceConfig]:
    unknown_source_slugs = sorted(requested_source_slugs - {source.slug for source in available_sources})
    if unknown_source_slugs:
        raise UnknownAssetSourcesError(unknown_source_slugs)

    if not requested_source_slugs:
        return available_sources

    return [source for source in available_sources if source.slug in requested_source_slugs]


def download_assets(
    settings: Settings,
    source_slugs: set[str],
) -> None:
    """Download Project Implicit study materials into the local assets tree."""
    assets_root = settings.PROJECT_IMPLICIT_ASSETS_DIR
    available_sources = load_download_source_configs(settings.DOWNLOAD_SOURCES_FILE).sources
    selected_sources = _select_sources(available_sources, source_slugs)

    assets_root.mkdir(parents=True, exist_ok=True)

    for source in selected_sources:
        try:
            _download_source(source, assets_root)
        except (FileURLRetrievalError, FolderContentsMaximumLimitError, ValueError, OSError) as error:
            raise AssetDownloadError(source.slug, error) from error

    _write_manifest(assets_root, available_sources)
