load("//tools/python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//:__subpackages__"])

py_library(
    name = "path",
    srcs = ["path.py"],
    visibility = ["//:__subpackages__"],
)

py_test(
    name = "path_test",
    srcs = ["path_test.py"],
    deps = [":path"],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

filegroup(
    name = "readme",
    srcs = ["README.md"],
    tags = ["markdown"],
)
