package(default_visibility = ["//:__subpackages__"])

filegroup(
    name = "readme",
    srcs = ["README.md"],
    tags = ["markdown"],
)

filegroup(
    name = "tooling",
    srcs = ["tooling.md"],
    tags = ["markdown"],
)

filegroup(
    name = "implicit_association_test_reference",
    srcs = ["Implementation of the Implicit Association Test.pdf"],
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
