load("@aspect_rules_lint//format:defs.bzl", "format_multirun")
load("@npm//:prettier/package_json.bzl", prettier = "bin")

package(default_visibility = ["//:__subpackages__"])

prettier.prettier_binary(
    name = "prettier",
    data = [
        "//:node_modules",
        "//:prettierrc",
    ],
    env = {"BAZEL_BINDIR": "."},
    fixed_args = [
        "--config=\"$$JS_BINARY__RUNFILES\"/$(rlocationpath //:prettierrc)",
        "--log-level=warn",
    ],
)

format_multirun(
    name = "format",
    css = ":prettier",
    html = ":prettier",
    javascript = ":prettier",
    markdown = ":prettier",
    python = "@aspect_rules_lint//format:ruff",
    starlark = "@buildifier_prebuilt//:buildifier",
    yaml = ":prettier",
    yaml_check_args = [
        "--check",
        "--log-level=warn",
    ],
    yaml_fix_args = [
        "--write",
        "--log-level=warn",
    ],
)

alias(
    name = "format_YAML_with_prettier",
    actual = ":format_YAML_with_yamlfmt",
)

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
