package(default_visibility = ["//:__subpackages__"])

filegroup(
    name = "build_bazel",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

filegroup(
    name = "asian-black-pleasant-unpleasant",
    srcs = ["asian-black-pleasant-unpleasant.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "asian-white-pleasant-unpleasant",
    srcs = ["asian-white-pleasant-unpleasant.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "female-male-science-liberal-arts",
    srcs = ["female-male-science-liberal-arts.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "thin-fat-pleasant-unpleasant",
    srcs = ["thin-fat-pleasant-unpleasant.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "white-black-pleasant-unpleasant",
    srcs = ["white-black-pleasant-unpleasant.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "young-old-female-male",
    srcs = ["young-old-female-male.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "young-old-pleasant-unpleasant",
    srcs = ["young-old-pleasant-unpleasant.yaml"],
    tags = ["yaml"],
)

filegroup(
    name = "readme",
    srcs = ["README.md"],
    tags = ["markdown"],
)
